### ISSUE TITLE
【練習ノート機能】設計書_10.グラフ分析

### ISSUE THREAD

**Issue by zukao** [zukao/ProjectHulk#10]
- [x] グラフ1計算式

**Comment by Aidzu** [comment]
@zukao 
【練習ノート機能】seet.10　グラフ分析＿参照　内、グラフ１の計算式の項目まとめといたので確認願います！

**Comment by zukao** [comment]
@Aidzu 
わかりやすいし完璧っす！
クローズしちゃってください〜
