### ISSUE TITLE
【練習ノート機能】設計_機能詳細

### ISSUE THREAD

**Issue by zukao** [zukao/ProjectHulk#2]
残タスク
レビュー合格でチェックをつけて完了
- [x] 自己ベスト入力
- [x] 練習記録入力
- [x] 自己ベスト参照
- [x] 自己ベスト修正
- [x] 自己ベスト削除
- [x] 練習記録参照
- [x] 練習記録修正
- [x] 練習記録削除
- [x] 部内ランキング参照
- [ ] ~~グラフ分析~~ #10

**Comment by zukao** [comment]
3/5に話した通りアサインを会津から亀井さんに変更します。
3/12までに読み込んで、スプレッドシートに書き込んであるレビュー対応と、見やすさの改善をしてください。
- [ ] キャッチアップ
- [ ] レビュー対応
- [ ] レイアウト修正

**Comment by zukao** [comment]
亀井さん休部により会津にアサイン変えました。

3/19までにもう一回レビュー投げられたらベスト

**Comment by zukao** [comment]
3/26までにレビューを必ず一回は投げるようにしてください！

**Comment by Aidzu** [comment]
とりあえずこまいところ修正しました。
グラフ計算式は未着手ですすまぬ～

**Comment by zukao** [comment]
@Aidzu 確認しました！開発スタートするのに充分な設計書になったと思うので本チケットはクローズして大丈夫です！
グラフの計算式については別のIssueに切り出しちゃいます。

今後、開発に入ったら設計書に必要な追記・修正を開発者側で加えていきたいと思います。
