### ISSUE TITLE
【練習ノート機能】画面遷移図

### ISSUE THREAD

**Issue by zukao** [zukao/ProjectHulk#5]
レビュー合格でチェック↓
- [x] 画面遷移図（PC）
- [x] 画面遷移図（スマホ）

**Comment by zukao** [comment]
3/5に話した通りアサインを亀井さんから会津に変更します。
3/12までにたたき台を作成し、レビューを投げるようにしてください。

**Comment by Aidzu** [comment]
一旦たたき台つくりましたので。
PCとスマホで相違あらば3/12のMTGでご意見いただければ！

**Comment by zukao** [comment]
レビューOKです。

**Comment by zukao** [comment]
MTGで決まった内容反映したらクローズしてください。

**Comment by zukao** [comment]
3/19までに完了

**Comment by Aidzu** [comment]
練習ノート機能の遷移図は完了です！
ただ、挙物語TOPからのほかの機能のところまだできてないので保留で。。。（詳細はGドライブ確認）
ここって今つめたほうがよいのかな？
今つめる必要なかったら一旦は完了なのでレスポンスまってるね！

**Comment by zukao** [comment]
そこに関しては一旦保留にしたいので必要になったら新規Issueとして起票します！
なのでこのIssueはクローズでok！

**Comment by zukao** [comment]
画面遷移図だけじゃなく今後の設計でスプレッドシートじゃ厳しいとこは以下のやつ試してみるといいかも！

・Astah（UML全般
http://astah.change-vision.com/ja/product/astah-community.html
・draw.io
https://www.draw.io/

使い方は少し難しそうなので調べてもらいながらにはなるけど・・・

**Comment by zukao** [comment]
レビューokなのでclosedに移しました。
